In [ ]:
import numpy as np

Create a null vector of size 10

In [14]:
vector = np.zeros(shape = (10))

print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth value which is 1 

In [15]:
vector1 = np.zeros(shape = (10))

vector1[4] = 1

print(vector1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [16]:
vector2 = np.arange(10, 50)

print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3x3 matrix with values ranging from 0 to 8 

In [40]:
matrix1 = np.arange(0, 9).reshape(3, 3)

print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a 10x10 array with random values and find the minimum and maximum values

In [43]:
matrix2 = np.random.rand(10, 10)

print(matrix2)

print(matrix2.max())

print(matrix2.min())

[[0.59156884 0.15044502 0.92837739 0.66260384 0.09705434 0.11354892
  0.2256185  0.33181508 0.03164479 0.8561811 ]
 [0.0868409  0.6998668  0.53499797 0.33972664 0.1765345  0.09548452
  0.31089066 0.49551203 0.26280532 0.62639992]
 [0.62680551 0.20033045 0.05324362 0.74694586 0.84250028 0.1397728
  0.82957505 0.61819729 0.65435723 0.22753985]
 [0.81087526 0.24891655 0.9215065  0.78352337 0.76740867 0.63182164
  0.06859192 0.67927697 0.06904585 0.67240178]
 [0.27450715 0.07399487 0.03213347 0.60900956 0.40424359 0.5704169
  0.92439585 0.85389459 0.42403333 0.06788905]
 [0.08359398 0.42301674 0.27862608 0.59647649 0.67844218 0.69587947
  0.6988675  0.10497251 0.94139517 0.98754273]
 [0.86741399 0.24313099 0.42854416 0.39886779 0.82140387 0.00569947
  0.33029314 0.36020808 0.63708197 0.81320869]
 [0.34397483 0.72673047 0.88215119 0.60863795 0.22794997 0.1510678
  0.20344721 0.17728498 0.20382715 0.2768878 ]
 [0.23192092 0.9754402  0.25669355 0.28099979 0.68204364 0.56373263
  0.13926871 0.

Create a 2d array with 1 on the border and 0 inside 

In [36]:
matrix3 = np.zeros(shape = (10, 10))

matrix3[0::matrix3.shape[1] - 1, :] = matrix3[:, 0::matrix3.shape[0] - 1] = 1

print(matrix3)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [57]:
matrix4 = np.random.rand(5, 3)

matrix5 = np.random.rand(3, 2)

print(np.dot(matrix4, matrix5))


[[1.14565035 1.04014755]
 [0.45006374 0.28882291]
 [0.35389803 0.22177351]
 [0.88458688 1.15581866]
 [1.46265445 1.26368444]]
